apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: kubesimplify-configmap
            key: username
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: kubesimplify-configmap
            key: database_name
